### ISSUE TITLE
automated email re reviewers

### ISSUE THREAD

**Issue by dblei** [JmlrOrg/webpage#1]
when we remind AEs to assign reviewers we send an automated email that says that they agreed to handle a paper.  in fact, we assigned it.  this has caused some confusion.

**Comment by fabianp** [comment]
Hi @dblei . I have changed the email from

"""
JMLR manuscript $manutag, version $manuver, "$manutitle," still has no requests for reviewers.  It has been $timesincereq since you agreed to serve as action editor for this manuscript.  Please submit your requests at http://jmlr.csail.mit.edu/manudb/ as soon as possible.
"""

to 
"""
JMLR manuscript $manutag, version $manuver, "$manutitle," still has no requests for reviewers.  It has been $timesincereq since you *were assigned as action editor for this manuscript*.  Please submit your requests at http://jmlr.csail.mit.edu/manudb/ as soon as possible.
"""

Let me know if you prefer a different formulation
