### ISSUE TITLE
Sometimes AE emails are flagged as spam

### ISSUE THREAD

**Issue by fabianp** [JmlrOrg/webpage#14]
Possible solution: send the email from a @jmlr.org address

**Comment by Metaxal** [comment]
It would be great if this could be fixed—I'm sure some potential reviewers are missing my emails because of this.

I believe the correct solution is to send emails from something like <jmlr-no-reply@jmlr.org> and populate the `reply-to` field with the AE's email address. That way, the email won't be seen as being sent from the wrong email address.

**Comment by fabianp** [comment]
This should now be fixed. We're sending emails from no-reply@jmlr2020.csail.mit.edu

**Comment by Metaxal** [comment]
Thanks for this. When was this change made? I've received very recent complaints about this. Can you try sending an email to me to test it out? (laurent orseau gmail)

**Comment by fabianp** [comment]
Hi Laurent,

This was done a couple days ago. I don't have an easy way to send you
emails unless you're an author of a paper under review. But let me know if
you experience any issues in the future

**Comment by Metaxal** [comment]
Okay, it's very recent then. I'll keep you posted. Thanks for looking into this!

**Comment by Metaxal** [comment]
Yes it works, awesome, thank you very much!
